--lots of smoke and stuff
return {
  ["tpbigshatter"] = {
    tpbigshatter = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 5,
      ground             = false,
      underwater         = 1,
      useairlos          = true,
      water              = false,
      unit				 = true,
	  alwaysVisible = 0,
	  properties = {
        alwaysVisible = 0,
        explosiongenerator = [[custom:tpbigshatter]],
	  airdrag            = 0.75,
        colormap           = [[0.8 0.8 0.9 0.9    0.8 0.5 0.9 0.6    0.6 0.6 0.9 0.3     0.8 0.8 0.8 0.1]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 10,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.5 r0.1, 0]],
        numparticles       = 30,
        particlelife       = 30,
        particlelifespread = 2,
        particlesize       = 4,
        particlesizespread = 3,
        particlespeed      =  6,
        particlespeedspread = 4.5,
        pos                = [[0, 0, 0]],
        sizegrowth         = -0.1,
        sizemod            = 1.0,
        texture            = [[dirt]],
      },
    },
  
  flyingdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 4,
      ground             = true,	  
      underwater         = 1,
      useairlos          = true,
      water              = true,
	  unit = false,
	  nounit = true,
      alwaysVisible = 0,
	  properties = {
        alwaysVisible = 0,
		airdrag            = 0.9,
        colormap           = [[0.4 0.3 0.2 0.8    0.2 0.15 0.1 0.8    0.2 0.15 0.1 0.7     0.2 0.15 0.1 0.7]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.3, 0]],
        numparticles       = 1,
        particlelife       = 50,
        particlelifespread = 10,
        particlesize       = 5,
        particlesizespread = 10,
        particlespeed      = 10.5,
        particlespeedspread = .1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 0.9,
        texture            = [[dirt]],
      },
    }, 
  
  },
}