return {
  ["tpexplosive"] = {
    --usedefaultexplosions = true,
    bang = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        heat               = 12,
        heatfalloff        = 1,
        maxheat            = 12,
        pos                = [[0, 5, 0]],
        size               = 15,
        sizegrowth         = 15,
        speed              = [[0, 0, 0]],
        texture            = [[dirt]],
      },
    },
    groundflash = {
      circlealpha        = .5,
      circlegrowth       = 20,
      flashalpha         = 1.8,
      flashsize          = 10,
      ttl                = 10,
      color = {
        [1]  = 1,
        [2]  = 0.7,
        [3]  = 0.4,
      },
    },
    	
  
  	flames = {
      air                = true,
      class              = [[explspike]],
      count              = 15,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.1,
        color              = [[0.9 ,0.2 ,0]],
        dir                = [[-15 r50,-15 r50,-15 r50]],
        length             = 2,
        width              = 20,
      },
    },	
	
	ringsmoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 3,
      ground             = true,
      underwater         = 1,
      useairlos          = true,
      water              = true,
      alwaysVisible = 0,
	  properties = {
        alwaysVisible = 0,
        explosiongenerator = [[custom:ringsmoke]],
		airdrag            = 0.95,
        colormap           = [[1 1 1 0.1   0.1 0.1 0.1 0.5 ]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 10,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.1 r0.01, 0]],
        numparticles       = 5,
        particlelife       = 10,
        particlelifespread = 40,
        particlesize       = 15,
        particlesizespread = 5,
        particlespeed      =  8,
        particlespeedspread = 5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[dirt]],
      },
    },
  },
  
}
