---respawn effect
return {
  ["tprespawn"] = {
    tprespawn = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 6,
      ground             = true,
      underwater         = 1,
      useairlos          = true,
      water              = true,
      alwaysVisible = 0,
	  properties = {
        alwaysVisible = 0,
        explosiongenerator = [[custom:tprespawn]],
	  airdrag            = 1,
        colormap           = [[1 1 1 0.9    0.9 0 0.9 0.6    1 0.0 0.1 0.95     0.9 0.9 0 0.8	0.3 1 0.3 0.1]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01 r0.1, 0]],
        numparticles       = 5,
        particlelife       = 20,
        particlelifespread = 10,
        particlesize       = 10,
        particlesizespread = 10,
        particlespeed      =  2,
        particlespeedspread = 8,
        pos                = [[0, 0, 0]],
        sizegrowth         = -0.05,
        sizemod            = 1.0,
        texture            = [[lines]],
      },
    },
  ["groundflash"] = {	
      flashSize = 1000,
      flashAlpha = 0.2,
      circleGrowth = 1.1,
      circleAlpha = 0.5,
      ttl = 15,
      color = [[1 1 1]],
      alwaysvisible=0,
	  air=1,
      ground=1,
      water=1,
   },   
  },
}
